### ISSUE TITLE
BUG - Graphql Server crash after change with nodmon

### ISSUE THREAD

**Issue by nicolas-grevin** [nicolas-grevin/graphsl-vs-apollo#1]
```bash
graphql-vs-apollo_graphql_server | [nodemon] restarting due to changes...
graphql-vs-apollo_graphql_server | [nodemon] starting `babel-node ./server.js`
graphql-vs-apollo_graphql_server | Mon, 10 Dec 2018 12:44:57 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
graphql-vs-apollo_graphql_server | test -change
graphql-vs-apollo_graphql_mongo | 2018-12-10T12:44:57.759+0000 I NETWORK  [listener] connection accepted from 192.168.96.3:40282 #3 (2 connections now open)
graphql-vs-apollo_graphql_mongo | 2018-12-10T12:44:57.768+0000 I NETWORK  [conn3] received client metadata from 192.168.96.3:40282 conn3: { driver: { name: "nodejs", version: "3.1.10" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-39-generic" }, platform: "Node.js v10.14.1, LE, mongodb-core: 3.1.9" }
graphql-vs-apollo_graphql_mongo | 2018-12-10T12:44:57.801+0000 I ACCESS   [conn3] Successfully authenticated as principal graphql_user on graphql_db
graphql-vs-apollo_graphql_server | INFO: Connected to mongo
graphql-vs-apollo_graphql_server | events.js:167
graphql-vs-apollo_graphql_server |       throw er; // Unhandled 'error' event
graphql-vs-apollo_graphql_server |       ^
graphql-vs-apollo_graphql_server | 
graphql-vs-apollo_graphql_server | Error: listen EADDRINUSE :::4441
graphql-vs-apollo_graphql_server |     at Server.setupListenHandle [as _listen2] (net.js:1286:14)
graphql-vs-apollo_graphql_server |     at listenInCluster (net.js:1334:12)
graphql-vs-apollo_graphql_server |     at Server.listen (net.js:1421:7)
graphql-vs-apollo_graphql_server |     at Function.listen (/app/node_modules/express/lib/application.js:618:24)
graphql-vs-apollo_graphql_server |     at _callee$ (/app/server.js:49:6)
graphql-vs-apollo_graphql_server |     at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:65:40)
graphql-vs-apollo_graphql_server |     at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:303:22)
graphql-vs-apollo_graphql_server |     at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:117:21)
graphql-vs-apollo_graphql_server |     at step (/app/server.js:94:191)
graphql-vs-apollo_graphql_server |     at /app/server.js:94:361
graphql-vs-apollo_graphql_server |     at process._tickCallback (internal/process/next_tick.js:68:7)
graphql-vs-apollo_graphql_server | Emitted 'error' event at:
graphql-vs-apollo_graphql_server |     at emitErrorNT (net.js:1313:8)
graphql-vs-apollo_graphql_server |     at process._tickCallback (internal/process/next_tick.js:63:19)
graphql-vs-apollo_graphql_mongo | 2018-12-10T12:44:57.825+0000 I NETWORK  [conn3] end connection 192.168.96.3:40282 (1 connection now open)
graphql-vs-apollo_graphql_server | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by nicolas-grevin** [comment]
resolved with `yarn clean:dependencies && yarn install`
